### ISSUE TITLE
Pawn takes unnecessarily long path

### ISSUE THREAD

**Issue by sparr** [KiameV/rimworld-pathavoid#3]
https://i.imgur.com/lFGqJVT.png

The pawn could get to its destination through either "hate" space. It chooses the longer path. Replace both red squares with orange and the problem goes away.

**Comment by KiameV** [comment]
This is out of scope of this mod, that's a problem with the game's path finding.
TBH the better path is probably the longer one since the shorter one will force the pawn to go through a light and a chair with wool on top of it (tiles with more than one item on it slow the pawn more) OR a light + mending table.

You could also try to adjust this mod's settings in Settings->Mod Settings->Path Avoid->Advanced to make the 'strong' less powerful and see if that makes any difference.
